**🌟Exercise 2: Dataset Loading and Initial Analysis**

Dataset #1: How Much Sleep Do Americans Really Get?

In [17]:
# Import the datasets from the required data sources

import pandas as pd

# Load the data directly into a DataFrame
sleeping_time_df = pd.read_csv("American_sleeping_time.csv")

# View the first few rows
sleeping_time_df.tail(60)

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
885,885,2003,Annual,8.17,0.073,Nonholiday weekdays,55 to 64 years,Sleeping,Women
886,886,2004,Annual,8.10,0.092,Nonholiday weekdays,55 to 64 years,Sleeping,Women
887,887,2005,Annual,8.17,0.093,Nonholiday weekdays,55 to 64 years,Sleeping,Women
888,888,2006,Annual,8.32,0.102,Nonholiday weekdays,55 to 64 years,Sleeping,Women
889,889,2007,Annual,7.98,0.105,Nonholiday weekdays,55 to 64 years,Sleeping,Women
890,890,2008,Annual,8.04,0.098,Nonholiday weekdays,55 to 64 years,Sleeping,Women
891,891,2009,Annual,8.27,0.101,Nonholiday weekdays,55 to 64 years,Sleeping,Women
892,892,2010,Annual,8.27,0.093,Nonholiday weekdays,55 to 64 years,Sleeping,Women
893,893,2011,Annual,8.35,0.097,Nonholiday weekdays,55 to 64 years,Sleeping,Women
894,894,2012,Annual,8.44,0.101,Nonholiday weekdays,55 to 64 years,Sleeping,Women
895,895,2013,Annual,8.29,0.103,Nonholiday weekdays,55 to 64 years,Sleeping,Women
896,896,2014,Annual,8.29,0.085,Nonholiday weekdays,55 to 64 years,Sleeping,Women
897,897,2015,Annual,8.47,0.116,Nonholiday weekdays,55 to 64 years,Sleeping,Women
898,898,2016,Annual,8.40,0.101,Nonholiday weekdays,55 to 64 years,Sleeping,Women
899,899,2017,Annual,8.29,0.113,Nonholiday weekdays,55 to 64 years,Sleeping,Women
900,900,2003,Annual,8.84,0.049,All days,65 years and over,Sleeping,Women
901,901,2004,Annual,8.93,0.054,All days,65 years and over,Sleeping,Women
902,902,2005,Annual,8.95,0.070,All days,65 years and over,Sleeping,Women
903,903,2006,Annual,8.82,0.071,All days,65 years and over,Sleeping,Women
904,904,2007,Annual,8.91,0.071,All days,65 years and over,Sleeping,Women
905,905,2008,Annual,8.94,0.070,All days,65 years and over,Sleeping,Women
906,906,2009,Annual,8.96,0.067,All days,65 years and over,Sleeping,Women
907,907,2010,Annual,9.04,0.072,All days,65 years and over,Sleeping,Women
908,908,2011,Annual,9.09,0.069,All days,65 years and over,Sleeping,Women
909,909,2012,Annual,8.87,0.068,All days,65 years and over,Sleeping,Women
910,910,2013,Annual,8.90,0.063,All days,65 years and over,Sleeping,Women
911,911,2014,Annual,9.02,0.066,All days,65 years and over,Sleeping,Women
912,912,2015,Annual,8.97,0.059,All days,65 years and over,Sleeping,Women
913,913,2016,Annual,8.97,0.054,All days,65 years and over,Sleeping,Women
914,914,2017,Annual,8.91,0.072,All days,65 years and over,Sleeping,Women
915,915,2003,Annual,9.18,0.072,Weekend days and holidays,65 years and over,Sleeping,Women
916,916,2004,Annual,9.05,0.067,Weekend days and holidays,65 years and over,Sleeping,Women
917,917,2005,Annual,9.28,0.119,Weekend days and holidays,65 years and over,Sleeping,Women
918,918,2006,Annual,8.94,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
919,919,2007,Annual,9.13,0.104,Weekend days and holidays,65 years and over,Sleeping,Women
920,920,2008,Annual,9.31,0.099,Weekend days and holidays,65 years and over,Sleeping,Women
921,921,2009,Annual,9.21,0.083,Weekend days and holidays,65 years and over,Sleeping,Women
922,922,2010,Annual,9.22,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
923,923,2011,Annual,9.29,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
924,924,2012,Annual,9.06,0.104,Weekend days and holidays,65 years and over,Sleeping,Women
925,925,2013,Annual,9.06,0.091,Weekend days and holidays,65 years and over,Sleeping,Women
926,926,2014,Annual,9.13,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
927,927,2015,Annual,9.30,0.086,Weekend days and holidays,65 years and over,Sleeping,Women
928,928,2016,Annual,9.10,0.081,Weekend days and holidays,65 years and over,Sleeping,Women
929,929,2017,Annual,9.15,0.100,Weekend days and holidays,65 years and over,Sleeping,Women
930,930,2003,Annual,8.70,0.060,Nonholiday weekdays,65 years and over,Sleeping,Women
931,931,2004,Annual,8.88,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
932,932,2005,Annual,8.81,0.081,Nonholiday weekdays,65 years and over,Sleeping,Women
933,933,2006,Annual,8.77,0.097,Nonholiday weekdays,65 years and over,Sleeping,Women
934,934,2007,Annual,8.82,0.088,Nonholiday weekdays,65 years and over,Sleeping,Women
935,935,2008,Annual,8.79,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
936,936,2009,Annual,8.86,0.083,Nonholiday weekdays,65 years and over,Sleeping,Women
937,937,2010,Annual,8.96,0.092,Nonholiday weekdays,65 years and over,Sleeping,Women
938,938,2011,Annual,9.02,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
939,939,2012,Annual,8.79,0.089,Nonholiday weekdays,65 years and over,Sleeping,Women
940,940,2013,Annual,8.83,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
941,941,2014,Annual,8.98,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
942,942,2015,Annual,8.83,0.074,Nonholiday weekdays,65 years and over,Sleeping,Women
943,943,2016,Annual,8.92,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
944,944,2017,Annual,8.81,0.091,Nonholiday weekdays,65 years and over,Sleeping,Women

In [ ]:
"""
The dataset contains information about Americans’ sleeping time across different years from 2003 to 2017. It includes variables such as year, period, average hours of sleep, standard error, activity type, age group, and sex. The data shown focuses on people aged 15 years and over, for both males and females, and records average sleeping hours annually.

For example, in 2003, Americans aged 15+ slept an average of 8.57 hours per day, while in 2007 the average was 8.57 hours.
"""

Dataset #2: Global Trends in Mental Health Disorder

In [15]:
# Load the data directly into a DataFrame
mental_health_df = pd.read_csv("Mental_health_disorder.csv")

# View the first few rows
mental_health_df.head(60)

C:\Users\LOMBE\AppData\Local\Temp\ipykernel_41612\614798371.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health_df = pd.read_csv("Mental_health_disorder.csv")

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
5,5,Afghanistan,AFG,1995,0.160076,0.698695,0.09098,4.828337,1.728112,4.104207,0.668746
6,6,Afghanistan,AFG,1996,0.160249,0.698914,0.089709,4.828083,1.737643,4.107500,0.667727
7,7,Afghanistan,AFG,1997,0.160554,0.699127,0.088372,4.827726,1.746891,4.110834,0.666220
8,8,Afghanistan,AFG,1998,0.160931,0.699372,0.08733,4.826971,1.756963,4.114438,0.664676
9,9,Afghanistan,AFG,1999,0.161311,0.699674,0.086267,4.826413,1.770791,4.117633,0.663428
10,10,Afghanistan,AFG,2000,0.161621,0.700015,0.086021,4.827047,1.788395,4.118610,0.662479
11,11,Afghanistan,AFG,2001,0.161957,0.700499,0.086517,4.831409,1.839123,4.121381,0.661158
12,12,Afghanistan,AFG,2002,0.162414,0.701141,0.087023,4.838318,1.934326,4.124928,0.659213
13,13,Afghanistan,AFG,2003,0.162916,0.70186,0.087189,4.845538,2.051106,4.125230,0.657354
14,14,Afghanistan,AFG,2004,0.163377,0.702556,0.088158,4.851512,2.163044,4.126384,0.656132
15,15,Afghanistan,AFG,2005,0.163706,0.703078,0.088933,4.854684,2.247443,4.126908,0.655686
16,16,Afghanistan,AFG,2006,0.163977,0.703517,0.090054,4.856685,2.321020,4.128638,0.656297
17,17,Afghanistan,AFG,2007,0.164302,0.703998,0.091688,4.858861,2.405564,4.129728,0.657709
18,18,Afghanistan,AFG,2008,0.164639,0.70448,0.093589,4.860437,2.483862,4.129656,0.659501
19,19,Afghanistan,AFG,2009,0.164932,0.704925,0.095166,4.861533,2.543884,4.129972,0.661185
20,20,Afghanistan,AFG,2010,0.16513,0.705313,0.097327,4.862777,2.571349,4.130874,0.662062
21,21,Afghanistan,AFG,2011,0.165272,0.705688,0.098638,4.864773,2.573170,4.130862,0.662254
22,22,Afghanistan,AFG,2012,0.165424,0.706086,0.099891,4.867283,2.576189,4.132485,0.662372
23,23,Afghanistan,AFG,2013,0.165579,0.706471,0.101291,4.869701,2.572396,4.134661,0.662433
24,24,Afghanistan,AFG,2014,0.165742,0.706876,0.103137,4.872256,2.562885,4.133526,0.662447
25,25,Afghanistan,AFG,2015,0.165895,0.707275,0.104445,4.875201,2.543144,4.135419,0.662276
26,26,Afghanistan,AFG,2016,0.166035,0.707686,0.105808,4.878875,2.513553,4.135694,0.661850
27,27,Afghanistan,AFG,2017,0.166158,0.708089,0.107142,4.882481,2.473934,4.136347,0.661217
28,28,Albania,ALB,1990,0.193413,0.695013,0.130782,3.327587,0.497616,2.139903,1.709465
29,29,Albania,ALB,1991,0.193393,0.695294,0.129102,3.330348,0.495687,2.141201,1.708135
30,30,Albania,ALB,1992,0.193405,0.695603,0.127063,3.333438,0.495337,2.143395,1.706053
31,31,Albania,ALB,1993,0.193438,0.695922,0.126019,3.336688,0.494085,2.145263,1.703585
32,32,Albania,ALB,1994,0.193491,0.696255,0.125402,3.340089,0.492630,2.150070,1.701142
33,33,Albania,ALB,1995,0.193559,0.696593,0.12532,3.343588,0.492058,2.154413,1.699120
34,34,Albania,ALB,1996,0.193675,0.696925,0.126148,3.346907,0.491589,2.161320,1.693187
35,35,Albania,ALB,1997,0.193865,0.697281,0.127301,3.350161,0.491548,2.170218,1.681620
36,36,Albania,ALB,1998,0.194094,0.6976,0.128839,3.353242,0.492290,2.179530,1.668865
37,37,Albania,ALB,1999,0.194328,0.697972,0.130729,3.356380,0.492855,2.188802,1.658553
38,38,Albania,ALB,2000,0.194541,0.698437,0.132704,3.360267,0.492401,2.195285,1.654338
39,39,Albania,ALB,2001,0.194812,0.698912,0.134932,3.364824,0.492592,2.201979,1.659040
40,40,Albania,ALB,2002,0.195214,0.699501,0.137541,3.370780,0.493751,2.208921,1.670158
41,41,Albania,ALB,2003,0.195677,0.700114,0.140335,3.376952,0.494039,2.216283,1.685102
42,42,Albania,ALB,2004,0.196139,0.700683,0.143047,3.382199,0.495812,2.222116,1.701433
43,43,Albania,ALB,2005,0.196538,0.701136,0.145738,3.385416,0.497503,2.223407,1.716585
44,44,Albania,ALB,2006,0.197004,0.701533,0.148561,3.387210,0.497997,2.222417,1.737167
45,45,Albania,ALB,2007,0.197636,0.701983,0.1517,3.388914,0.497442,2.217203,1.766903
46,46,Albania,ALB,2008,0.198306,0.7024,0.154945,3.390168,0.497332,2.210642,1.798550
47,47,Albania,ALB,2009,0.198905,0.702783,0.157738,3.391018,0.498324,2.206033,1.824955
48,48,Albania,ALB,2010,0.199308,0.703064,0.160337,3.391246,0.500270,2.203342,1.838566
49,49,Albania,ALB,2011,0.199588,0.703313,0.16242,3.391181,0.502703,2.202291,1.843256
50,50,Albania,ALB,2012,0.199863,0.703539,0.165446,3.390807,0.505621,2.202192,1.847375
51,51,Albania,ALB,2013,0.200134,0.70376,0.167105,3.390195,0.508049,2.203098,1.850358
52,52,Albania,ALB,2014,0.200392,0.70397,0.16941,3.389319,0.510089,2.203684,1.851517
53,53,Albania,ALB,2015,0.20063,0.704161,0.171095,3.388212,0.513158,2.204454,1.850252
54,54,Albania,ALB,2016,0.200845,0.704335,0.172627,3.386891,0.515036,2.206507,1.845972
55,55,Albania,ALB,2017,0.201025,0.70448,0.174046,3.385245,0.517614,2.208414,1.837955
56,56,Algeria,DZA,1990,0.193582,0.802893,0.189024,4.976553,1.300832,3.732597,0.644399
57,57,Algeria,DZA,1991,0.193207,0.802986,0.18699,4.977260,1.319511,3.717979,0.644877
58,58,Algeria,DZA,1992,0.192891,0.803126,0.185064,4.978074,1.338333,3.706706,0.645308
59,59,Algeria,DZA,1993,0.192647,0.803287,0.183793,4.978894,1.358713,3.694652,0.645669

In [9]:
"""
The dataset contains information about Global trand in mental health across different years from 1990 to 2017. The general variables are: Entity(countries), entity code and year. The health variables in percentage are : schizophrenia, depression, and disorders (bipolar, eating, anxiety, alcohol and drug use)

"""

Dataset #3: Credit Card Approvals

In [6]:
# Load the data directly into a DataFrame
credit_card_df = pd.read_csv("crx.csv")

# View the first few rows
credit_card_df.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [8]:
# Load the data directly into a DataFrame
clean_dataset_df = pd.read_csv("clean_dataset.csv")

# View the first few rows
clean_dataset_df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

**🌟Exercise 3: Identifying Data Types**